//! DISK-0006 R2 — enrollment E2E through real gRPC over TLS.
//!
//! The production EnrollmentService listener split (TLS-only, no `client_ca_root`)
//! is deferred to a follow-up backlog item — see `datarim/backlog.md`. Until that
//! lands, this test exercises the client side end-to-end against an in-process
//! tonic server bound to loopback, mirroring the eventual production topology
//! (TLS but **not** mTLS for the enrollment endpoint).
//!
//! Asserted invariants:
//! - `IssuePendingToken` requires the admin bearer in `x-disk-admin-token`
//!   metadata; client correctly attaches it and the server sees the same value.
//! - `Enroll` round-trips the opaque token + CSR PEM; the CSR generated by
//!   `gen_keypair_and_csr` is a valid PKCS#10 with the expected subject CN.
//! - The client returns the server-issued cert PEM verbatim.

#![cfg(unix)]

use std::sync::{Arc, Mutex};
use std::time::Duration;

use disk_client::{gen_keypair_and_csr, EnrollmentClient};
use disk_proto::disk::{
    enrollment_service_server::{EnrollmentService, EnrollmentServiceServer},
    EnrollRequest, EnrollResponse, EnrollmentTokenRequest, EnrollmentTokenResponse,
    RevokePendingRequest, RevokePendingResponse,
};
use rcgen::{generate_simple_self_signed, CertifiedKey};
use tokio::net::TcpListener;
use tonic::transport::{Identity, Server, ServerTlsConfig};
use tonic::{Request, Response, Status};

const ADMIN_TOKEN: &str = "test-admin-token";
const ISSUED_TOKEN: [u8; 32] = [0xAB; 32];
const RETURNED_CERT_PEM: &str =
    "-----BEGIN CERTIFICATE-----\nSTUB-CERT\n-----END CERTIFICATE-----\n";

#[derive(Default)]
struct Capture {
    admin_token_seen: Mutex<Option<String>>,
    csr_pem_seen: Mutex<Option<Vec<u8>>>,
    node_id_seen: Mutex<Option<String>>,
}

struct StubEnrollment {
    cap: Arc<Capture>,
}

#[tonic::async_trait]
impl EnrollmentService for StubEnrollment {
    async fn issue_pending_token(
        &self,
        req: Request<EnrollmentTokenRequest>,
    ) -> Result<Response<EnrollmentTokenResponse>, Status> {
        let admin = req
            .metadata()
            .get("x-disk-admin-token")
            .and_then(|v| v.to_str().ok())
            .map(|s| s.to_owned());
        *self.cap.admin_token_seen.lock().unwrap() = admin.clone();
        if admin.as_deref() != Some(ADMIN_TOKEN) {
            return Err(Status::permission_denied("bad admin"));
        }
        let inner = req.into_inner();
        Ok(Response::new(
            EnrollmentTokenResponse {
                opaque_token: ISSUED_TOKEN.to_vec(),
                expires_at_ms: 9_999_999_999,
            }
            .with_hint(inner.node_id_hint),
        ))
    }

    async fn enroll(
        &self,
        req: Request<EnrollRequest>,
    ) -> Result<Response<EnrollResponse>, Status> {
        let r = req.into_inner();
        *self.cap.csr_pem_seen.lock().unwrap() = Some(r.csr_pem.clone());
        *self.cap.node_id_seen.lock().unwrap() = Some(r.node_id_hint.clone());
        if r.opaque_token != ISSUED_TOKEN {
            return Err(Status::failed_precondition("token mismatch"));
        }
        Ok(Response::new(EnrollResponse {
            client_cert_pem: RETURNED_CERT_PEM.as_bytes().to_vec(),
            ca_chain_pem: b"CHAIN".to_vec(),
            expires_at_ms: 1_000_000_000,
        }))
    }

    async fn revoke_pending(
        &self,
        _req: Request<RevokePendingRequest>,
    ) -> Result<Response<RevokePendingResponse>, Status> {
        Err(Status::unimplemented("not exercised"))
    }
}

trait WithHint {
    fn with_hint(self, hint: String) -> Self;
}
impl WithHint for EnrollmentTokenResponse {
    fn with_hint(self, _hint: String) -> Self {
        // hint is not in the response wire — function exists for clarity that
        // the stub deliberately ignores the field. Returning self unchanged.
        self
    }
}

struct Fixture {
    server_url: String,
    ca_pem: Vec<u8>,
    capture: Arc<Capture>,
    _shutdown: tokio::sync::oneshot::Sender<()>,
}

async fn spawn_stub_server() -> Fixture {
    // Loopback-bound listener with auto-assigned port. We resolve the port
    // first so the URL is known before the server task starts polling.
    let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind 0");
    let local = listener.local_addr().expect("local_addr");
    let port = local.port();

    // Self-signed cert covers SNI = "localhost". Client connects via
    // https://localhost:<port> so SNI matches.
    let CertifiedKey { cert, signing_key: key_pair } =
        generate_simple_self_signed(vec!["localhost".into(), "127.0.0.1".into()]).unwrap();
    let cert_pem = cert.pem();
    let key_pem = key_pair.serialize_pem();
    let ca_pem = cert_pem.clone().into_bytes();

    let identity = Identity::from_pem(&cert_pem, &key_pem);
    // TLS-only — NO client_ca_root. This mirrors the eventual production
    // enrollment listener topology (proto §DISK-0005 v1.1 «Public RPC»).
    let tls = ServerTlsConfig::new().identity(identity);

    let capture = Arc::new(Capture::default());
    let svc = StubEnrollment {
        cap: capture.clone(),
    };

    let (tx, rx) = tokio::sync::oneshot::channel::<()>();

    let incoming = tokio_stream::wrappers::TcpListenerStream::new(listener);

    tokio::spawn(async move {
        Server::builder()
            .tls_config(tls)
            .expect("apply tls")
            .add_service(EnrollmentServiceServer::new(svc))
            .serve_with_incoming_shutdown(incoming, async {
                let _ = rx.await;
            })
            .await
            .expect("server terminated");
    });

    // Tiny readiness wait — bind+listen happens before spawn but tonic
    // does TLS plumbing before accepting; 50ms is generous on loopback.
    tokio::time::sleep(Duration::from_millis(100)).await;

    Fixture {
        server_url: format!("https://localhost:{port}"),
        ca_pem,
        capture,
        _shutdown: tx,
    }
}

#[tokio::test]
async fn admin_pending_token_round_trip() {
    let fx = spawn_stub_server().await;

    let client = EnrollmentClient::connect(&fx.server_url, Some(&fx.ca_pem), false)
        .await
        .expect("connect");

    let resp = client
        .issue_pending_token(ADMIN_TOKEN, "new-node-01", 3600)
        .await
        .expect("issue_pending_token");

    assert_eq!(resp.opaque_token, ISSUED_TOKEN.to_vec());
    assert_eq!(resp.expires_at_ms, 9_999_999_999);
    assert_eq!(
        fx.capture.admin_token_seen.lock().unwrap().as_deref(),
        Some(ADMIN_TOKEN),
        "server must observe the admin bearer in x-disk-admin-token metadata"
    );
}

#[tokio::test]
async fn admin_pending_token_rejects_missing_bearer() {
    let fx = spawn_stub_server().await;

    let client = EnrollmentClient::connect(&fx.server_url, Some(&fx.ca_pem), false)
        .await
        .expect("connect");

    let err = client
        .issue_pending_token("wrong-admin", "new-node-01", 3600)
        .await
        .expect_err("must reject wrong admin token");
    match err {
        disk_client::EnrollmentError::Status(s) => {
            assert_eq!(s.code(), tonic::Code::PermissionDenied);
        }
        other => panic!("expected Status, got {other:?}"),
    }
}

#[tokio::test]
async fn enroll_round_trip_with_real_csr() {
    let fx = spawn_stub_server().await;
    let node_id = "macos-laptop-01";

    let (_key_pem, csr_pem) = gen_keypair_and_csr(node_id).expect("csr");

    let client = EnrollmentClient::connect(&fx.server_url, Some(&fx.ca_pem), false)
        .await
        .expect("connect");

    let resp = client
        .enroll(ISSUED_TOKEN.to_vec(), csr_pem.into_bytes(), node_id.into())
        .await
        .expect("enroll");

    assert_eq!(resp.client_cert_pem, RETURNED_CERT_PEM.as_bytes());
    assert_eq!(resp.expires_at_ms, 1_000_000_000);

    let csr_seen = fx
        .capture
        .csr_pem_seen
        .lock()
        .unwrap()
        .clone()
        .expect("server saw a CSR");
    let csr_str = String::from_utf8(csr_seen).unwrap();
    assert!(
        csr_str.contains("BEGIN CERTIFICATE REQUEST"),
        "server received a valid PKCS#10 PEM"
    );
    assert_eq!(
        fx.capture.node_id_seen.lock().unwrap().as_deref(),
        Some(node_id)
    );
}
